# -*- coding: utf-8 -*-
"""EGPO_LoRa2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfahFL2bG1iYzBo8Q_dxPgSLo3rxCFwJ
"""

# Geometry-driven gateway placement for LoRa on a bridge.
# This notebook uses fuzzy c-means clustering with LoRa-specific constraints
# (max coverage radius, 1 gateway per N nodes, minimum node–gateway distance,
# elevation margin above nodes) to select gateway locations.
# For each dataset (25–200 nodes), it searches over a range of cluster counts,
# selects C* using the Xie–Beni index, and exports the resulting gateway
# positions for ns-3 evaluation of energy consumption and ULDR.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa
import os

# ============================================================
# 0. CENTRAL CONFIG - EDIT HERE FOR ALL RUNS
# ============================================================
CONFIG = {
    'csv_file': "node_locations_50_SaintNazaire.csv",
    'lora_coverage_m': 200,
    'use_lora_fcm': True,
    'min_dist_penalty': 15.0,
    'repulsion_strength': 200,
    'min_elev_above_nodes': 1.5,
    'node_ratio': 8,
    'hard_cap': 10,
    'show_plots': True,
    'output_dir': 'results/'
}

# ============================================================
# 1. NORMALIZATION & UTILS (scikit‑style)
# ============================================================

def normalize_columns(u):
    """Normalize columns so each column sums to 1 (fuzzy partition matrix)."""
    return u / np.sum(u, axis=1, keepdims=True)

def normalize_power_columns(d, exponent):
    """SciKit‑style safe normalization of distances with exponent."""
    d = d.astype(np.float64)
    d = d / np.max(d, axis=1, keepdims=True)
    d = np.fmax(d, np.finfo(d.dtype).eps)

    if exponent < 0:
        d /= np.min(d, axis=1, keepdims=True)
        d = d ** exponent
    else:
        d = d ** exponent

    return normalize_columns(d)

def range_limit(d, max_dist=2000.0):
    """Cap extreme distances to avoid outliers dominating clustering."""
    d = np.asarray(d)
    d[d >= max_dist] = 10000.0
    return d

# ============================================================
# 2. GEO ↔ LOCAL ENU
# ============================================================

def latlon_to_local_enu(lat, lon, height, lat0, lon0, height0=0.0):
    lat  = np.asarray(lat, dtype=float)
    lon  = np.asarray(lon, dtype=float)

    lat_rad  = np.radians(lat)
    lon_rad  = np.radians(lon)
    lat0_rad = np.radians(lat0)
    lon0_rad = np.radians(lon0)

    R = 6371000.0
    dlon = lon_rad - lon0_rad
    dlat = lat_rad - lat0_rad

    x = dlon * np.cos(lat0_rad) * R    # East
    y = dlat * R                       # North
    z = np.asarray(height) - height0   # Up

    return np.column_stack([x, y, z])

def local_enu_to_latlon(x, y, z, lat0, lon0, height0=0.0):
    R = 6371000.0
    lat0_rad = np.radians(lat0)
    lon0_rad = np.radians(lon0)

    lat_rad = lat0_rad + y / R
    lon_rad = lon0_rad + x / (R * np.cos(lat0_rad))
    height = height0 + z

    return np.degrees(lat_rad), np.degrees(lon_rad), height

def load_nodes_csv_to_xyz(csv_file):
    df = pd.read_csv(csv_file)
    lat, lon, height = df['latitude'].values, df['longitude'].values, df['height_m'].fillna(0).values


    lat0, lon0 = lat[0], lon[0]
    height0 = 0.0

    print(f"🌍 Arc origin: Node 0 at ({lat0:.8f}, {lon0:.8f})")

    X = latlon_to_local_enu(lat, lon, height, lat0, lon0, height0)
    return X, (lat0, lon0, height0), df['node_id'].values

# ============================================================
# 3. PLOTTING
# ============================================================
def plot_path_arc(X, node_ids, title="Node Path"):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    # Path distance (reveals true arc)
    path_dist = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(X, axis=0), axis=1))])

    # Height vs path distance = PERFECT parabola
    ax1.plot(path_dist, X[:,2], 'o-', linewidth=3, markersize=8)
    ax1.set_xlabel('Distance along path (m)'); ax1.set_ylabel('Height (m)')
    ax1.set_title('Height Arc Profile')
    ax1.grid(True, alpha=0.3)

    # XY trajectory (your actual layout)
    ax2.plot(X[:,0], X[:,1], 'o-', linewidth=3, markersize=8)
    ax2.scatter(X[0,0], X[0,1], c='green', s=200, marker='*', label='Node 0')
    ax2.scatter(X[-1,0], X[-1,1], c='red', s=200, marker='*', label='Node 49')
    ax2.set_xlabel('East (m)'); ax2.set_ylabel('North (m)')
    ax2.set_title('True XY Layout')
    ax2.legend(); ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()


def plot_nodes_enu(X, title_prefix="Nodes", show_plots=True):
  if not show_plots:
    return

  N = len(X)
  fig = plt.figure(figsize=(12, 5))

  ax1 = fig.add_subplot(121, projection='3d')
  s1 = ax1.scatter(X[:,0], X[:,1], X[:,2], c=X[:,2], cmap='viridis', s=40)
  ax1.set_xlabel('East (m)'); ax1.set_ylabel('North (m)'); ax1.set_zlabel('Up (m)')
  ax1.set_title(f'{title_prefix} (N={N}) - 3D')

  ax2 = fig.add_subplot(122)
  s2 = ax2.scatter(X[:,0], X[:,1], c=X[:,2], cmap='viridis', s=40)
  ax2.set_xlabel('East (m)'); ax2.set_ylabel('North (m)')
  ax2.set_title(f'{title_prefix} (N={N}) - Top View')
  plt.colorbar(s2, ax=ax2, label='Height (m)')
  plt.tight_layout()
  plt.show()

def plot_nodes_and_gateways(X_nodes, X_gateways, C_star, show_plots=True):
    if not show_plots:
        return

    fig = plt.figure(figsize=(12, 5))

    ax1 = fig.add_subplot(121, projection='3d')
    ax1.scatter(X_nodes[:,0], X_nodes[:,1], X_nodes[:,2], c='lightblue', s=30, alpha=0.7)
    ax1.scatter(X_gateways[:,0], X_gateways[:,1], X_gateways[:,2], c='red', s=150, marker='^')
    ax1.set_title(f'LoRa Bridge: {C_star} Gateways - 3D')

    ax2 = fig.add_subplot(122)
    ax2.scatter(X_nodes[:,0], X_nodes[:,1], c=X_nodes[:,2], cmap='viridis', s=30, alpha=0.7)
    ax2.scatter(X_gateways[:,0], X_gateways[:,1], c='red', s=150, marker='^', edgecolors='black')
    ax2.set_title(f'LoRa Bridge: {C_star} Gateways - Top View')
    ax2.set_xlabel('East (m)'); ax2.set_ylabel('North (m)')

    plt.tight_layout()
    plt.show()

# ============================================================
# 4. LoRa‑OPTIMIZED FCM + XIE–BENI
# ============================================================

def lora_distance_with_repulsion(X, centers, min_dist, repulsion_strength):
    """GENTLE LoRa repulsion - soft penalty for close nodes."""
    euclidean_dist = np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2)

    # Soft repulsion: quadratic penalty, activates <15m
    too_close = np.minimum(euclidean_dist, min_dist)
    repulsion = repulsion_strength * ((min_dist - too_close) / min_dist) ** 2

    return euclidean_dist + repulsion

def hybrid_fcm_3d(X, n_clusters, m=2.0, error=1e-5, max_iter=300, seed=42):
    """Original FCM (no LoRa penalty)."""
    X = np.asarray(X, dtype=float)
    N = X.shape[0]

    np.random.seed(seed)
    U = np.random.rand(N, n_clusters)
    U = normalize_columns(U)
    U = np.fmax(U, np.finfo(np.float64).eps)

    for it in range(max_iter):
        U_old = U.copy()
        Um = U ** m
        centers = (Um.T @ X) / Um.sum(axis=0)[:, None]

        D = np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2)
        D = np.fmax(D, np.finfo(np.float64).eps)
        D = range_limit(D)

        U = normalize_power_columns(D, -2.0 / (m - 1.0))
        if np.linalg.norm(U - U_old) < error:
            break

    return centers, U, it + 1

def hybrid_fcm_3d_lora(X, n_clusters, m=2.0, error=1e-5, max_iter=300,
                      min_dist_penalty=15.0, repulsion_strength=100.0, seed=42):
    """LoRa-aware FCM with GENTLE repulsion."""
    X = np.asarray(X, dtype=float)
    N = X.shape[0]

    np.random.seed(seed)
    U = np.random.rand(N, n_clusters)
    U = normalize_columns(U)
    U = np.fmax(U, np.finfo(np.float64).eps)

    for it in range(max_iter):
        U_old = U.copy()
        Um = U ** m
        centers = (Um.T @ X) / Um.sum(axis=0)[:, None]

        D = lora_distance_with_repulsion(X, centers, min_dist_penalty, repulsion_strength)
        D = range_limit(D)

        U = normalize_power_columns(D, -2.0 / (m - 1.0))
        if np.linalg.norm(U - U_old) < error:
            break

    return centers, U, it + 1

def xie_beni_index_3d(X, centers, U, m=2.0):
    N = X.shape[0]
    D = np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2)
    num = np.sum((U ** m) * (D ** 2))

    C = centers.shape[0]
    if C < 2:
        return np.inf

    center_dists = np.linalg.norm(centers[:, None, :] - centers[None, :, :], axis=2)
    mask = ~np.eye(C, dtype=bool)
    min_center_dist2 = np.min(center_dists[mask] ** 2)

    return num / (N * min_center_dist2)


# ============================================================
# 5. LoRa BRIDGE OPTIMIZATION
# ============================================================

def gentle_min_distance_push(centers, X, min_dist=10.0, push_factor=0.5):
    """GENTLE push away from nodes - no hard constraint."""
    centers = centers.copy()
    for i in range(len(centers)):
        dists = np.linalg.norm(X - centers[i], axis=1)
        nearest_node_idx = np.argmin(dists)
        current_dist = dists[nearest_node_idx]

        if current_dist < min_dist:
            # Gentle proportional push
            push_distance = (min_dist - current_dist) * push_factor
            direction = centers[i] - X[nearest_node_idx]
            direction /= np.linalg.norm(direction) + 1e-8
            centers[i] = X[nearest_node_idx] + direction * (current_dist + push_distance)

    return centers

def enforce_gateway_elevation(centers, X_nodes, min_elev_above_nodes):
    """Ensure ALL gateways are elevated above highest node + buffer."""
    centers = centers.copy()
    max_node_height = np.max(X_nodes[:, 2])
    target_height = max_node_height + min_elev_above_nodes

    # Preserve XY cluster centers, elevate Z only
    centers[:, 2] = np.maximum(centers[:, 2], target_height)

    print(f"🗼 Elevated gateways: max_node_h={max_node_height:.1f}m → target_h={target_height:.1f}m")
    print(f"   New heights: {centers[:, 2].round(1)}m")

    return centers

def lora_bridge_C_max(X, lora_coverage_m, node_ratio=15, hard_cap=10):
    N = len(X)
    span_xy = np.max(np.linalg.norm(X[:, :2] - np.mean(X[:, :2], axis=0), axis=1)) * 2 + 100

    C_coverage = max(1, int(np.ceil(span_xy / lora_coverage_m)))
    C_nodes = max(1, N // node_ratio)

    print(f"🌉 Bridge span: {span_xy - 100:.0f}m")
    print(f"📡 LoRa coverage: {lora_coverage_m}m/gateway")
    print(f"👥 Node rule: 1 gw per {node_ratio} nodes")

    return min(C_coverage, C_nodes, hard_cap) + 1

def find_optimal_C(X, config):
    C_max = lora_bridge_C_max(X, config['lora_coverage_m'],
                            config['node_ratio'], config['hard_cap'])
    C_min = 1
    N = len(X)
    max_nodes_per_gw = 40
    C_min = max(C_min, int(np.ceil(N / max_nodes_per_gw)) - 1)

    print(f"\n🔍 Testing C=[{C_min}, {C_max}] for LoRa bridge...")

    best_C, best_xb = C_min, np.inf
    for C in range(C_min, C_max + 1):
        if config['use_lora_fcm']:
            centers, U, iters = hybrid_fcm_3d_lora(
                X, C, min_dist_penalty=config['min_dist_penalty'],
                repulsion_strength=config['repulsion_strength']
            )
        else:
            centers, U, iters = hybrid_fcm_3d(X, C)

        # GENTLE push only if needed
        centers = gentle_min_distance_push(centers, X, config['min_dist_penalty'])

        xb = xie_beni_index_3d(X, centers, U)

        min_dist_to_nodes = np.min(np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2), axis=0)
        min_all = min_dist_to_nodes.min()

        status = "✓" if min_all >= 10 else "⚠️"
        print(f"  C={C}: XB={xb:.6e}, min gw-node={min_all:.1f}m {status}")

        if xb < best_xb:
            best_xb = xb
            best_C = C

    return best_C, best_xb

# ============================================================
# 6. MAIN PIPELINE
# ============================================================

def lora_bridge_pipeline(config):
    csv_file = config['csv_file']
    output_dir = config['output_dir']

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    print("=== 🚀 LoRa Bridge Gateway Optimizer (GENTLE LoRa Penalties + Height) ===")

    X, origin, node_ids = load_nodes_csv_to_xyz(csv_file)
    lat0, lon0, h0 = origin
    plot_path_arc(X, node_ids)  # ← Shows your perfect height arc

    nodes_enu_df = pd.DataFrame({
        'node_id': node_ids,
        'x_enu_m': X[:, 0],
        'y_enu_m': X[:, 1],
        'z_enu_m': X[:, 2],
        'origin_lat': lat0,
        'origin_lon': lon0,
        'origin_height': h0
    })
    nodes_enu_df.to_csv(os.path.join(output_dir, 'lora_nodes_enu.csv'), index=False)

    plot_nodes_enu(X, "LoRa Bridge Nodes", config['show_plots'])

    C_star, xb_star = find_optimal_C(X, config)

    # Final clustering
    if config['use_lora_fcm']:
        centers, U, iters = hybrid_fcm_3d_lora(
            X, C_star, min_dist_penalty=config['min_dist_penalty'],
            repulsion_strength=config['repulsion_strength']
        )
    else:
        centers, U, iters = hybrid_fcm_3d(X, C_star)

    centers = gentle_min_distance_push(centers, X, config['min_dist_penalty'])
    centers = enforce_gateway_elevation(centers, X, config['min_elev_above_nodes'])

    min_dist_to_nodes = np.min(np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2), axis=0)
    print(f"\n✅ FINAL: C*={C_star}, XB={xb_star:.2e}")
    print(f"   Min gw-node distance: {min_dist_to_nodes.min():.1f}m (target >10m)")

    plot_nodes_and_gateways(X, centers, C_star, config['show_plots'])

    lat_gw, lon_gw, h_gw = local_enu_to_latlon(centers[:,0], centers[:,1], centers[:,2], lat0, lon0, h0)

    pd.DataFrame({
        'gateway_id': range(C_star),
        'longitude': lon_gw,
        'latitude': lat_gw,
        'height': h_gw
    }).to_csv(os.path.join(output_dir, 'lora_gateways_ns3.csv'), index=False)

    pd.DataFrame({
        'gateway_id': range(C_star),
        'x_enu_m': centers[:,0],
        'y_enu_m': centers[:,1],
        'z_enu_m': centers[:,2],
        'origin_lat': lat0, 'origin_lon': lon0, 'origin_height': h0
    }).to_csv(os.path.join(output_dir, 'lora_gateways_enu.csv'), index=False)

    print(f"\n✅ LoRa Bridge Optimized!")
    print(f"   Files saved to: {output_dir}")
    print("   Files: lora_gateways_ns3.csv + lora_gateways_enu.csv + lora_nodes_enu.csv")

    return C_star, centers, U

# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    C_star, centers, U = lora_bridge_pipeline(CONFIG)

