# -*- coding: utf-8 -*-
"""PAGPO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlH2MA0_Iit3FMmJfhRxaKQFiV0RjG6e
"""

# This notebook combines fuzzy c-means clustering with Radio Mobile
# propagation maps to compute a cost that accounts for RSSI margin,
# range penalties, LoRa-specific repulsion, and elevation constraints.
# For each dataset (25–200 nodes) and terrain/coverage map (e.g., water
# bridge vs. mountain bridge), it searches over gateway counts,
# selects C* via a propagation-aware Xie–Beni index, and exports the
# gateway positions for ns-3 evaluation of energy consumption and ULDR.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa
import re
import os

# ============================================================
# 0. CENTRAL CONFIG - EDIT HERE FOR ALL RUNS
# ============================================================

CONFIG = {
    'csv_file': "node_locations_200_SaintNazaire.csv",
    'txt_file': "pontsn200.txt",
    'gateway_ids': [0,1,2,3,4],
    'C_min': 1,
    'C_max': 6,
    'm': 2.0,
    'P_sens': -127.0,
    'max_dist': 1e6,
    'min_dist_penalty': 15.0,
    'repulsion_strength': 200,
    'min_elev_above_nodes': 1.5,
    'node_ratio': 8,
    'hard_cap': 10,
    'show_plots': True,
    'output_dir': 'prop_results/'
}

# ============================================================
# 1. NORMALIZATION & UTILS (scikit-style)
# ============================================================

def normalize_columns(u):
    """Normalize rows so each row sums to 1 (fuzzy membership per node)."""
    return u / np.sum(u, axis=1, keepdims=True)

def normalize_power_columns(d, exponent):
    """SciKit-style safe normalization of distances with exponent."""
    d = d.astype(np.float64)
    d = d / np.max(d, axis=1, keepdims=True)
    d = np.fmax(d, np.finfo(d.dtype).eps)

    if exponent < 0:
        d /= np.min(d, axis=1, keepdims=True)
        d = d ** exponent
    else:
        d = d ** exponent

    return normalize_columns(d)

def range_limit(d, max_dist):
    """Cap extreme costs to avoid numerical issues."""
    d = np.asarray(d)
    d[d >= max_dist] = max_dist
    return d

# ============================================================
# 2. RADIO MOBILE TXT PARSER
# ============================================================

def parse_radiomobile_txt(txt_file, gateway_ids):
    """Parse pontdemauzac.txt format."""
    data = []
    in_table = False

    with open(txt_file, 'r') as f:
        for line in f:
            line = line.strip()

            if line.startswith('Latitude') and 'Longitude' in line:
                in_table = True
                continue

            if not in_table or not line or line.startswith('Fixed unit'):
                continue

            parts = re.split(r'\s+', line)
            if len(parts) >= 4:
                try:
                    lat = float(parts[0])
                    lon = float(parts[1])
                    rx_str = parts[2]
                    best_unit = int(parts[3])
                    rx_dbm = float(rx_str)

                    data.append({
                        'latitude': lat,
                        'longitude': lon,
                        'rssi_dbm': rx_dbm,
                        'best_unit': best_unit
                    })
                except (ValueError, IndexError):
                    continue

    df = pd.DataFrame(data)

    print(f"📡 Loaded {len(df)} coverage points from {txt_file}")
    print(f" RSSI range: {df['rssi_dbm'].min():.1f} to {df['rssi_dbm'].max():.1f} dBm")
    print(f" Gateways in use: {sorted(set(df['best_unit']) & set(gateway_ids))}")

    return df

# ============================================================
# 3. GEO ↔ LOCAL ENU
# ============================================================

def latlon_to_local_enu(lat, lon, height, lat0, lon0, height0=0.0):
    lat = np.asarray(lat, dtype=float)
    lon = np.asarray(lon, dtype=float)

    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)
    lat0_rad = np.radians(lat0)
    lon0_rad = np.radians(lon0)

    R = 6371000.0

    dlon = lon_rad - lon0_rad
    dlat = lat_rad - lat0_rad

    x = dlon * np.cos(lat0_rad) * R  # East
    y = dlat * R  # North
    z = np.asarray(height) - height0  # Up

    return np.column_stack([x, y, z])

def local_enu_to_latlon(x, y, z, lat0, lon0, height0=0.0):
    R = 6371000.0

    lat0_rad = np.radians(lat0)
    lon0_rad = np.radians(lon0)

    lat_rad = lat0_rad + y / R
    lon_rad = lon0_rad + x / (R * np.cos(lat0_rad))
    height = height0 + z

    return np.degrees(lat_rad), np.degrees(lon_rad), height

def load_nodes_csv_to_xyz(csv_file):
    df = pd.read_csv(csv_file)

    lon = df['longitude'].values
    lat = df['latitude'].values
    height = df['height_m'].fillna(0.0).values

    lat0, lon0 = lat[0], lon[0]
    height0 = 0.0

    print(f"🌍 Origin: lat={lat0:.6f}, lon={lon0:.6f}, h={height0:.1f}m")
    print(f"📊 Loaded {len(df)} nodes")

    X = latlon_to_local_enu(lat, lon, height, lat0, lon0, height0)

    return X, (lat0, lon0, height0), df['node_id'].values

# ============================================================
# 4. PLOTTING
# ============================================================

def plot_coverage_map(df_coverage, gateway_positions=None, show_plots=True):
    if not show_plots:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    scatter = ax1.scatter(
        df_coverage['longitude'],
        df_coverage['latitude'],
        c=df_coverage['rssi_dbm'],
        cmap='RdYlGn',
        s=20,
        alpha=0.7
    )

    ax1.set_xlabel('Longitude')
    ax1.set_ylabel('Latitude')
    ax1.set_title('Radio Mobile Coverage (RSSI dBm)')
    plt.colorbar(scatter, ax=ax1, label='RSSI (dBm)')

    if gateway_positions is not None:
        g_lon = gateway_positions['longitude']
        g_lat = gateway_positions['latitude']
        ax1.scatter(g_lon, g_lat, c='red', s=200, marker='^', edgecolors='black', label='Gateways')
        ax1.legend()

    ax2.hist(df_coverage['rssi_dbm'], bins=30, edgecolor='black', alpha=0.7)
    ax2.set_xlabel('RSSI (dBm)')
    ax2.set_ylabel('Count')
    ax2.set_title('RSSI Distribution')
    ax2.axvline(df_coverage['rssi_dbm'].mean(), color='red', linestyle='--', label='Mean')
    ax2.legend()

    plt.tight_layout()
    plt.show()

def plot_nodes_enu(X, title_prefix="Nodes", show_plots=True):
    if not show_plots:
        return

    N = len(X)

    fig = plt.figure(figsize=(12, 5))

    ax1 = fig.add_subplot(121, projection='3d')
    s1 = ax1.scatter(X[:,0], X[:,1], X[:,2], c=X[:,2], cmap='viridis', s=40)
    ax1.set_xlabel('East (m)')
    ax1.set_ylabel('North (m)')
    ax1.set_zlabel('Up (m)')
    ax1.set_title(f'{title_prefix} (N={N}) - 3D')

    ax2 = fig.add_subplot(122)
    s2 = ax2.scatter(X[:,0], X[:,1], c=X[:,2], cmap='viridis', s=40)
    ax2.set_xlabel('East (m)')
    ax2.set_ylabel('North (m)')
    ax2.set_title(f'{title_prefix} (N={N}) - Top View')

    plt.colorbar(s2, ax=ax2, label='Height (m)')
    plt.tight_layout()
    plt.show()

def plot_nodes_and_gateways(X_nodes, X_gateways, C_star, show_plots=True):
    if not show_plots:
        return

    fig = plt.figure(figsize=(12, 5))

    ax1 = fig.add_subplot(121, projection='3d')
    ax1.scatter(X_nodes[:,0], X_nodes[:,1], X_nodes[:,2], c='lightblue', s=30, alpha=0.7)
    ax1.scatter(X_gateways[:,0], X_gateways[:,1], X_gateways[:,2], c='red', s=150, marker='^')
    ax1.set_title(f'LoRa Bridge: {C_star} Gateways - 3D')

    ax2 = fig.add_subplot(122)
    ax2.scatter(X_nodes[:,0], X_nodes[:,1], c=X_nodes[:,2], cmap='viridis', s=30, alpha=0.7)
    ax2.scatter(X_gateways[:,0], X_gateways[:,1], c='red', s=150, marker='^', edgecolors='black')
    ax2.set_title(f'LoRa Bridge: {C_star} Gateways - Top View')
    ax2.set_xlabel('East (m)')
    ax2.set_ylabel('North (m)')

    plt.tight_layout()
    plt.show()

# ============================================================
# 5. LoRa REPLUSION + HEIGHT CONSTRAINTS (FROM FIRST CODE)
# ============================================================

def lora_distance_with_repulsion(X, centers, min_dist, repulsion_strength):
    """GENTLE LoRa repulsion - soft penalty for close nodes."""
    euclidean_dist = np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2)

    # Soft repulsion: quadratic penalty, activates <15m
    too_close = np.minimum(euclidean_dist, min_dist)
    repulsion = repulsion_strength * ((min_dist - too_close) / min_dist) ** 2

    return euclidean_dist + repulsion

def gentle_min_distance_push(centers, X, min_dist=15.0, push_factor=0.5):
    """GENTLE push away from nodes - no hard constraint."""
    centers = centers.copy()

    for i in range(len(centers)):
        dists = np.linalg.norm(X - centers[i], axis=1)
        nearest_node_idx = np.argmin(dists)
        current_dist = dists[nearest_node_idx]

        if current_dist < min_dist:
            # Gentle proportional push
            push_distance = (min_dist - current_dist) * push_factor
            direction = centers[i] - X[nearest_node_idx]
            direction /= np.linalg.norm(direction) + 1e-8
            centers[i] = X[nearest_node_idx] + direction * (current_dist + push_distance)

    return centers

def enforce_gateway_elevation(centers, X_nodes, min_elev_above_nodes):
    """Ensure ALL gateways are elevated above highest node + buffer."""
    centers = centers.copy()

    max_node_height = np.max(X_nodes[:, 2])
    target_height = max_node_height + min_elev_above_nodes

    # Preserve XY cluster centers, elevate Z only
    centers[:, 2] = np.maximum(centers[:, 2], target_height)

    print(f"🗼 Elevated gateways: max_node_h={max_node_height:.1f}m → target_h={target_height:.1f}m")
    print(f" New heights: {centers[:, 2].round(1)}m")

    return centers

def propagation_c_max(X, node_ratio=8, hard_cap=5):
    """Estimate max clusters based on node count and coverage."""
    N = len(X)
    span_xy = np.max(np.linalg.norm(X[:, :2] - np.mean(X[:, :2], axis=0), axis=1)) * 2 + 100
    C_nodes = max(1, N // node_ratio)
    return min(C_nodes, hard_cap) + 1

# ============================================================
# 6. RADIO MOBILE PROPAGATION LOOKUP
# ============================================================

class RadioMobileInterpolator:
    def __init__(self, df_coverage, gateway_positions, lat0, lon0, h0, P_sens):
        self.df = df_coverage
        self.gateways = gateway_positions
        self.origin = (lat0, lon0, h0)
        self.P_sens = P_sens

        self.X_coverage = latlon_to_local_enu(
            self.df['latitude'],
            self.df['longitude'],
            np.zeros_like(self.df['latitude']),
            lat0, lon0, h0
        )

        self.X_gateways = latlon_to_local_enu(
            self.gateways['latitude'],
            self.gateways['longitude'],
            self.gateways['height_m'].fillna(180.0),
            lat0, lon0, h0
        )

        print(f"🔍 Interpolator ready: {len(self.df)} points, {len(self.gateways)} gateways")

    def get_rssi_nearest(self, node_xyz, gw_idx):
        distances = np.linalg.norm(self.X_coverage - node_xyz, axis=1)

        k = 5
        idx = np.argsort(distances)[:k]

        d = distances[idx]
        weights = 1.0 / (d + 1e-6)
        weights /= np.sum(weights)

        return np.sum(weights * self.df.iloc[idx]['rssi_dbm'].values)

    def get_rssi_from_map(self, node_xyz, gw_xyz):
        gw_distances = np.linalg.norm(self.X_gateways - gw_xyz, axis=1)
        gw_idx = np.argmin(gw_distances)
        return self.get_rssi_nearest(node_xyz, gw_idx)

def propagation_cost_matrix(
    X_nodes,
    centers,
    interpolator,
    max_range_m=800,
    range_soft_m=500,
    M_soft=25.0,
    K_bad=100.0,
    eps=1e-3
):
    """
    RSSI cost × range penalty.
    """
    N = X_nodes.shape[0]
    C = centers.shape[0]
    D = np.zeros((N, C), dtype=float)

    for i in range(N):
        for j in range(C):
            dist_ij = np.linalg.norm(X_nodes[i] - centers[j])

            if dist_ij > max_range_m:
                D[i, j] = K_bad * 10
            else:
                range_penalty = 1.0 + (dist_ij - range_soft_m) / (max_range_m - range_soft_m)
                range_penalty = np.maximum(range_penalty, 1.0)

                P_ij = interpolator.get_rssi_from_map(X_nodes[i], centers[j])
                M_ij = P_ij - interpolator.P_sens

                if M_ij <= 0:
                    rssi_cost = np.exp(-M_ij / 5.0)
                else:
                    M_eff = M_soft * (1.0 - np.exp(-M_ij / M_soft))
                    rssi_cost = 1.0 / (M_eff + eps)

                D[i, j] = rssi_cost * range_penalty

    D = np.clip(D, 1e-6, np.percentile(D, 95))
    D = D / (np.median(D) + 1e-6)

    return D

# ============================================================
# 7. PROPAGATION-AWARE FCM WITH LoRa REPLUSION
# ============================================================

def fcm_propagation_aware_lora(
    X,
    n_clusters,
    config,
    interpolator,
    error=1e-5,
    max_iter=300,
    seed=42
):
    """Propagation-aware FCM WITH LoRa repulsion."""
    X = np.asarray(X, dtype=float)
    N, D_dim = X.shape
    n_clusters = int(n_clusters)

    np.random.seed(int(seed))
    U = np.random.uniform(0.0, 1.0, size=(N, n_clusters)).astype(np.float64)
    U = normalize_columns(U)
    U = np.fmax(U, np.finfo(np.float64).eps)

    Um = U ** config['m']
    centers = (Um.T @ X) / np.maximum(Um.sum(axis=0)[:, None], np.finfo(np.float64).eps)

    for it in range(max_iter):
        U_old = U.copy()
        centers_old = centers.copy()

        prop_cost = propagation_cost_matrix(X, centers, interpolator)
        repulsion_cost = lora_distance_with_repulsion(
            X,
            centers,
            config['min_dist_penalty'],
            config['repulsion_strength']
        )

        D = prop_cost * (1 + 0.3 * repulsion_cost)

        D = np.fmax(D, np.finfo(np.float64).eps)
        D = range_limit(D, config['max_dist'])

        exponent = -2.0 / (config['m'] - 1.0)
        U = normalize_power_columns(D, exponent)

        Um = U ** config['m']
        centers = (Um.T @ X) / np.maximum(Um.sum(axis=0)[:, None], np.finfo(np.float64).eps)

        delta_u = np.linalg.norm(U - U_old)
        delta_c = np.linalg.norm(centers - centers_old)

        if delta_u < error and delta_c < error:
            print(f" Converged at iteration {it+1}")
            break

    return centers, U, it + 1

def xie_beni_index_prop(X, centers, U, config, interpolator=None):
    N = X.shape[0]

    prop_cost = propagation_cost_matrix(X, centers, interpolator)
    D = np.fmax(prop_cost, np.finfo(np.float64).eps)

    prop_weights = 1 / (1 + np.mean(D, axis=0))  # Favor C with better avg RSSI
    num = np.sum((U ** config['m']) * (D ** 2))

    # amplify bad links
    num *= (1 + 0.5 * np.std(D))

    C = centers.shape[0]
    if C < 2:
        return 1e6

    center_dists = np.linalg.norm(centers[:, None, :] - centers[None, :, :], axis=2)
    mask = ~np.eye(C, dtype=bool)

    dists2 = center_dists[mask] ** 2

    # --- soft-min separation (more stable in dense deployments) ---
    k = max(1, len(dists2) // 4)
    min_center_dist2 = np.mean(np.sort(dists2)[:k])

    # --- floor to prevent collapse ---
    expected_spacing = (np.max(X[:,0]) - np.min(X[:,0])) / centers.shape[0]
    min_center_dist2 = max(min_center_dist2, (0.5 * expected_spacing) ** 2)

    if min_center_dist2 < 1e-6:
        return 1e6

    max_nodes_per_gw = config.get('max_nodes_per_gw', 30.0)
    cluster_load = np.sum(U, axis=0)
    avg_load = N / centers.shape[0]

    density_penalty = np.mean((cluster_load / avg_load) ** 2)
    if N < 99:
      c_bias = C / np.log(N + 1)
    else:
      alpha = 1.5
      c_bias = (C ** alpha) / np.log(N + 1)

    return num / (min_center_dist2 * density_penalty * c_bias)

# ============================================================
# 8. C* SEARCH WITH PROPAGATION + LoRa CONSTRAINTS
# ============================================================

def find_optimal_C_propagation(X, interpolator, config):
    C_max = min(
        config['C_max'],
        propagation_c_max(X, config['node_ratio'], config['hard_cap'])
    )
    C_min = config['C_min']

    N = len(X)
    max_nodes_per_gw = 40
    C_min = max(C_min, int(np.ceil(N / max_nodes_per_gw))- 1)

    best_C = C_min
    best_xb = np.inf

    print(f"\n🔍 Propagation+LoRa search for C in [{C_min}, {C_max}]")

    for C in range(C_min, C_max + 1):
        centers, U, iters = fcm_propagation_aware_lora(
            X,
            C,
            config,
            interpolator,
            max_iter=100,
            seed=42+C
        )

        centers = gentle_min_distance_push(centers, X, config['min_dist_penalty'])
        centers = enforce_gateway_elevation(centers, X, config['min_elev_above_nodes'])

        xb = xie_beni_index_prop(X, centers, U, config, interpolator)

        print(f" C={C}: XB_prop={xb:.6e} (iters={iters})")

        if xb < best_xb and np.isfinite(xb):
            best_xb = xb
            best_C = C

    print(f"\n✅ Propagation+LoRa OPTIMAL C* = {best_C} (XB_prop={best_xb:.6e})")
    return best_C, best_xb

# ============================================================
# 9. MAIN PIPELINE WITH FULL LoRa CONSTRAINTS
# ============================================================

def propagation_aware_bridge_pipeline(config):
    output_dir = config['output_dir']
    os.makedirs(output_dir, exist_ok=True)

    print("=== 🚀 Propagation+LoRa Bridge Optimizer (Repulsion + Height) ===")

    X_nodes, origin, node_ids = load_nodes_csv_to_xyz(config['csv_file'])
    lat0, lon0, h0 = origin

    df_coverage = parse_radiomobile_txt(config['txt_file'], config['gateway_ids'])
    plot_coverage_map(df_coverage, show_plots=config['show_plots'])

    gateway_positions = pd.DataFrame({
        'node_id': config['gateway_ids'],
        'latitude': [43.37778, 43.37774, 43.37701, 43.37766, 43.37762],
        'longitude': [1.29000, 1.29005, 1.29010, 1.29014, 1.29019],
        'height_m': [180.8, 180.0, 179.0, 178.5, 177.8]
    })

    interpolator = RadioMobileInterpolator(
        df_coverage,
        gateway_positions,
        lat0,
        lon0,
        h0,
        config['P_sens']
    )

    nodes_enu_df = pd.DataFrame({
        'node_id': node_ids,
        'x_enu_m': X_nodes[:, 0],
        'y_enu_m': X_nodes[:, 1],
        'z_enu_m': X_nodes[:, 2],
        'origin_lat': lat0,
        'origin_lon': lon0,
        'origin_height': h0
    })

    nodes_enu_df.to_csv(os.path.join(output_dir, 'prop_nodes_enu.csv'), index=False)

    plot_nodes_enu(X_nodes, "Propagation+LoRa Nodes", config['show_plots'])

    C_star, xb_star = find_optimal_C_propagation(X_nodes, interpolator, config)

    centers, U, iters = fcm_propagation_aware_lora(
        X_nodes,
        C_star,
        config,
        interpolator,
        max_iter=300,
        seed=42
    )

    centers = gentle_min_distance_push(centers, X_nodes, config['min_dist_penalty'])
    centers = enforce_gateway_elevation(centers, X_nodes, config['min_elev_above_nodes'])

    min_dist_to_nodes = np.min(
        np.linalg.norm(
            X_nodes[:, None, :] - centers[None, :, :],
            axis=2
        ),
        axis=0
    )

    print(f"\n✅ FINAL: C*={C_star}, XB_prop={xb_star:.2e}, iters={iters}")
    print(f" Min gw-node distance: {min_dist_to_nodes.min():.1f}m (target >{config['min_dist_penalty']}m)")

    plot_nodes_and_gateways(X_nodes, centers, C_star, config['show_plots'])

    lat_gw, lon_gw, h_gw = local_enu_to_latlon(
        centers[:,0],
        centers[:,1],
        centers[:,2],
        lat0,
        lon0,
        h0
    )

    pd.DataFrame({
        'gateway_id': range(C_star),
        'longitude': lon_gw,
        'latitude': lat_gw,
        'height_m': h_gw
    }).to_csv(os.path.join(output_dir, 'prop_gateways_ns3.csv'), index=False)

    pd.DataFrame({
        'gateway_id': range(C_star),
        'x_enu_m': centers[:,0],
        'y_enu_m': centers[:,1],
        'z_enu_m': centers[:,2],
        'origin_lat': lat0,
        'origin_lon': lon0,
        'origin_height': h0
    }).to_csv(os.path.join(output_dir, 'prop_gateways_enu.csv'), index=False)

    print(f"\n✅ SUCCESS! Files saved to: {output_dir}")
    print(" Files: prop_gateways_ns3.csv, prop_gateways_enu.csv, prop_nodes_enu.csv")

    return C_star, centers, U, interpolator

# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    C_star, centers, U, interpolator = propagation_aware_bridge_pipeline(CONFIG)
